#!/bin/bash
#$ -V
#$ -cwd
#$ -N sfb_dflowfm
#$ -m bea
#$ -M emman@sfei.org

# add dflowfm to path
export PATH=/opt/software/delft/dfm/r52184-opt/bin:$PATH

# now navigate to the directory with the *.mdu file and replace
# test.mdu below with the name of your mdu file

# create 16 partitions for parallel run
dflowfm --partition:ndomains=16:icgsolver=6 test.mdu >partition.txt

# execute parallel run
mpiexec -n 16 dflowfm --autostartstop test.mdu > out.txt 2> err.txt
